hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 41000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 80000
    socket-timeout-millis: 80000
  routes:
    microservice-a:
      path: /service-a/**
      serviceid: microservice-a
      stripPrefix: false
      sensitiveHeaders:

    microservice-b:
      path: /service-b/**
      serviceId: microservice-b
      stripPrefix: false
      sensitiveHeaders:
server:
  port: 4000
